### PR TITLE
Create Product_Development_Strategy file and Explain Steps

### PR DESCRIPTION
**Pull request by auroraborie**
In this PR, I list the steps it takes to create a product development strategy as a product manager. Product managers often have to juggle between various cross functional teams in a company and having a product development strategy is critical in the organization of these teams for the product's creation process. 

This article walks readers through each step of creating a PDS including industry standard frameworks, key terminology of product teams such as KPI, and external links for readers to learn more about the process. These topics are written with the intention of helping readers understand how to use a PDS to launch a new product to market with the best fit. 

**Additions:**
- Added a drop down menu to help readers navigate the wiki article with ease
- Wrote sections on: What is a Product Development Strategy and Why is it Important, Conduct Market Research, Conduct Primary Research, Build a Prototype and test the Product, Launch the Product
- Included images and other media links to provide reader with more examples and further reading 

**Why**
The work of a product manager, which is to communicate, design, and lead each stage of the product development process can be transferrable to help guide students in their own projects. This article gives students a concrete organizational methodology of the **product development strategy** to help create their own features.

This article serves as a practical guide to help students develop their own product development strategies for future projects, or to aid future product managers in the adoption of industry standard practices for the product development process.

### CODE REVIEW

**Review by diegogonza112 — APPROVED** [review]
Great Stuff Aurora! Really informative!

**Comment by RuilinP** [comment]
Really detailed and well-structured. Personal opinion though, do you think if you can add some extra "case studies" or graphs to differentiate the terms? Also,sometimes, as someone almost never studied business/economy, the post  seems sort of "assuming the reader are familiar with with the field". For example, what does COGS stand for?

**Comment by RuilinP** [comment]
Also, a reminder that the file you pushed didn't end with extension of .md

**Comment by auroraborie** [comment]
> Also, a reminder that the file you pushed didn't end with extension of .md

Thanks for all your feedback! I incorporated your suggestions such as changing technical acronyms to their real name and included more infographics and diagrams for ease of understanding of formulas and testing frameworks.

**Pull request merged**
