### PR TITLE
Completed first draft of my Assignment 2 topic

### PR DESCRIPTION
**Pull request by rowanArora**
I believe I provided a comprehensive yet not too detailed overview of how AI impacts the world of software engineers. 

Specifically what AI-based tools are widely used by programmers, what frameworks are widely used by programmers to build their own AI models, and a few of the most widely used AI model types and when they should be used.

Please provide me with any feedback you think will help! Thank you!

### CODE REVIEW

**Review by SpecialThing44 — CHANGES_REQUESTED** [review]
I think this is a really comprehensive and great start.
I think you should consider adding a link under each framework/model to have more direct resources than just those listed at the bottom of the page

**Review by jeanine5 — CHANGES_REQUESTED** [review]
Your first draft is very solid! There is a lot of important information included in an easy-to-read way. Maybe consider structuring the bullet points in a more consistent way. For example, you indent some bullet points to show limitations and others to show examples and some to list functionality. I do like the bullet points, though.

**Comment by rowanArora** [comment]
> Your first draft is very solid! There is a lot of important information included in an easy-to-read way. Maybe consider structuring the bullet points in a more consistent way. For example, you indent some bullet points to show limitations and others to show examples and some to list functionality. I do like the bullet points, though.

Thank you so much for the review! I will try to restructure the bullet points in a more consistent way to make it a bit easier to read. Thank you!

**Review by jeanine5 — APPROVED** [review]
The updated structure looks great! There is more consistency throughout the file. Good job!

**Comment by rowanArora** [comment]
> The updated structure looks great! There is more consistency throughout the file. Good job!

Thank you so much!

**Review by SpecialThing44 — APPROVED** [review]
I apologize for my oversight, this looks great!

**Comment by rowanArora** [comment]
> I apologize for my oversight, this looks great!

No worries! Thank you for the review nonetheless.

**Pull request merged**
