### PR TITLE
525 an introduction to chakra UI intro installation setup benefits drawbacks

### PR DESCRIPTION
**Pull request by PierreLessard**
#525

This PR is to create a introduction on Chakra UI and will include the following subtopics:
- Installation
- Setup
- Benefits & Drawbacks

### CODE REVIEW

**Review by jasonfyw — CHANGES_REQUESTED** [review]
Looks great! The benefits and drawbacks are a particularly valuable addition and are helpful for anyone looking for a frontend component library. However, I think this could benefit from a brief section about using UI components themselves

**Comment by PierreLessard** [comment]
Sounds good! I added the brief "Using UI Components" section as you asked.

**Review by jasonfyw — APPROVED** [review]
Perfect! Thank you for the addition. Looks good to merge!

**Review by PierreLessard — COMMENTED** [review]
Added

**Pull request merged**
