### PR TITLE
Introduction to database schemas and ER diagarms

### PR DESCRIPTION
**Pull request by DaneshKohina**
I created an introduction to database schemas and ER diagrams for students who may have a project that requires them to create one. I defined some terminology at the beginning and also went through a simple example of a hospital schema for making appointments.

### CODE REVIEW

**Comment by ThomasShimUoft** [comment]
I could be good to add more resources and examples.

**Comment by ThomasShimUoft** [comment]
A question: I see FK and PK which I assume it signifies foreign keys and primary keys but it seems like that took the place of its data type. Is it possible to specify a data type like "int" and also that it is a primary key? I would think that is important for attributes like ID's, some organizations use numbers for ID's or others strings like UofT utorids.

**Comment by DaneshKohina** [comment]
> I could be good to add more resources and examples.

Thanks Tom. I added in 2 more resources that should be of help.

> A question: I see FK and PK which I assume it signifies foreign keys and primary keys but it seems like that took the place of its data type. Is it possible to specify a data type like "int" and also that it is a primary key? I would think that is important for attributes like ID's, some organizations use numbers for ID's or others strings like UofT utorids.

That's a good catch Tom it can confuse some students who are new to databases. I created note in bold to state that why I had put PK and FK as in the form of the data type in my ER diagrams. You can certainly say something like Integer PK however this just depends on how each individual/team wants to draw up their diagrams. In my case I just decided to not include the data type.

**Review by ThomasShimUoft — APPROVED** [review]
It looks great. You took in feedback and improved the work. This is something I am learning in CSC343 and definitely will help students in their future CSC301 projects as well.

**Comment by absolute-xero7** [comment]
The article provides a clear and comprehensive introduction to database schemas and ER diagrams, using a practical example of a hospital appointment booking system. It effectively covers the definition of a database schema, and its components (tables, fields, relationships, and constraints), and demonstrates the process of creating a schema through ER diagrams.
I couldn't see a proper definition of ER diagram anywhere, consider adding a clear definition. You could also adds some challenges faced when using ER Diagrams.

**Comment by DaneshKohina** [comment]
> The article provides a clear and comprehensive introduction to database schemas and ER diagrams, using a practical example of a hospital appointment booking system. It effectively covers the definition of a database schema, and its components (tables, fields, relationships, and constraints), and demonstrates the process of creating a schema through ER diagrams. I couldn't see a proper definition of ER diagram anywhere, consider adding a clear definition. You could also adds some challenges faced when using ER Diagrams.

Thank you for the feedback Prahlad. I have now added a definition of ER diagrams as well as a note on one of their main limitations. I have already provided a link to a useful source about ER diagrams so that students can learn more about them. The main aim of my article is how to come up with a schema using ER diagrams so I don't want too put too much focus on ER diagrams itself. Hence I provided a link to a useful resource.

**Comment by absolute-xero7** [comment]
> > The article provides a clear and comprehensive introduction to database schemas and ER diagrams, using a practical example of a hospital appointment booking system. It effectively covers the definition of a database schema, and its components (tables, fields, relationships, and constraints), and demonstrates the process of creating a schema through ER diagrams. I couldn't see a proper definition of ER diagram anywhere, consider adding a clear definition. You could also adds some challenges faced when using ER Diagrams.
> 
> Thank you for the feedback Prahlad. I have now added a definition of ER diagrams as well as a note on one of their main limitations. I have already provided a link to a useful source about ER diagrams so that students can learn more about them. The main aim of my article is how to come up with a schema using ER diagrams so I don't want too put too much focus on ER diagrams itself. Hence I provided a link to a useful resource.

Well done Danish, everything looks good now.

**Pull request merged**
