### PR TITLE
Create Intro_to_Svelte.md

### PR DESCRIPTION
**Pull request by DanielZFLiu**
An introduction to svelte and how to learn more about it

### CODE REVIEW

**Comment by HanliJiang13** [comment]
This pull request is a valuable contribution for beginners interested in Svelte. The guide is clear, concise, and covers the essential aspects of getting started with Svelte. With a few enhancements, you can possibly include a concluding section, it would be an even more effective learning resource.

**Comment by DanielZFLiu** [comment]
> This pull request is a valuable contribution for beginners interested in Svelte. The guide is clear, concise, and covers the essential aspects of getting started with Svelte. With a few enhancements, you can possibly include a concluding section, it would be an even more effective learning resource.

Thanks for the suggestion! I will add a concluding section.

**Comment by HanliJiang13** [comment]
Maybe you can add a subsection on Component Lifecycle to explain the lifecycle methods in Svelte (onMount, onDestroy, etc.). This might help beginners to get more details from this artcle. Since when I was learning Svelte, I found that the lifecycle methods is really helpful.

**Comment by DanielZFLiu** [comment]
> Maybe you can add a subsection on Component Lifecycle to explain the lifecycle methods in Svelte (onMount, onDestroy, etc.). This might help beginners to get more details from this artcle. Since when I was learning Svelte, I found that the lifecycle methods is really helpful.

Thanks, will do!

**Comment by HanliJiang13** [comment]
It looks much better for a beginners to get start with Svelte. One more suggestion about learning resources, for now we have some basic tutorial links, including some links to advanced tutorials, online courses might be better for those who want to learn more about Svelte. Thank you!

**Comment by DanielZFLiu** [comment]
Alright, thanks!

**Comment by DanielZFLiu** [comment]
Directly committed it!

**Pull request merged**
