### PR TITLE
Adding Introductory description to Lean Methodology

### PR DESCRIPTION
**Pull request by ThomasShimUoft**
Created Lean.md in Software_Engineering directory and added a Lean bullet point in Software_Engineering.md

### CODE REVIEW

**Comment by DaneshKohina** [comment]
This looks good Thomas. However I do have some suggestions to make. The main suggestion is to add a section that talks about the main differences and similarities to other popular development methodologies such as agile or waterfall? Also why don't you add a simple example workflow so that students can see the lean methodology in use. Finally also consider adding one or two more disadvantage to the lean methodology so that you have an even amount of advantages and disadvantages.

**Comment by ThomasShimUoft** [comment]
Okay thank you for the feedback will add those points.

**Comment by ThomasShimUoft** [comment]
I have added more disadvantages to the Lean methodology, I have also added differences between lean, agile and waterfall. There is also already a simple example workflow (although it is high overview), this framework that is mentioned in the commit is sufficient.

**Review by DaneshKohina — COMMENTED** [review]
This is great work Tom.
Thanks for taking my changes into account. I like the addition of a Lean methodology this will definitely help future students.

**Pull request merged**
