### PR TITLE
Added "Introduction to Prompt Engineering"

### PR DESCRIPTION
**Pull request by sfnicholas**
Created section for Technical Techniques and Function Calling within Applications

### CODE REVIEW

**Review by Adrianhui123 — CHANGES_REQUESTED** [review]
1.  Add a heading for Function Calling section (## in markdown) for clarity and organization of the mark down file
2.  In the technical techniques section, add some appliction tips so software students can follow along and would be more beneficial for software practices

**Review by Adrianhui123 — CHANGES_REQUESTED** [review]
ensure consistency in the use of headers. For application tips, i would consider adding a ### for a good hierarchical structure

**Review by Adrianhui123 — CHANGES_REQUESTED** [review]
For function calling,  focus on the technical accuracy of the function calling process and the code example. Ensure that the example provided is realistic and can be practically implemented, double check that

**Comment by sfnicholas** [comment]
I double checked my code. I believe it has clear enough technical accuracy. Do you think my code example is easy to understand?

**Comment by Adrianhui123** [comment]
> I double checked my code. I believe it has clear enough technical accuracy. Do you think my code example is easy to understand?

Ok i see

**Pull request merged**
