### PR TITLE
created count_vectorizer.md

### PR DESCRIPTION
**Pull request by nomiko0626**

### CODE REVIEW

**Comment by kaavyakalani26** [comment]
I think you can make a table of contents for you page making it easier for a user to follow the page.

**Review by kaavyakalani26 — CHANGES_REQUESTED** [review]
I think you can make a table of contents for you page making it easier for a user to follow the page.

**Review by nomiko0626 — COMMENTED** [review]
You're correct. I'll include a table of contents.

**Comment by kaavyakalani26** [comment]
The Contents table looks good. Though there is a way to link the contents to the topics in md which you can explore!

Also noticed your renaming the file and moving to the right folder, something I was going to comment so that is great!

**Comment by kaavyakalani26** [comment]
Additionally, maybe you can add some more usages?

**Comment by nomiko0626** [comment]
Thanks for the feedback! I've made all the changes you've requested.

**Review by kaavyakalani26 — CHANGES_REQUESTED** [review]
It looks good! Just one last small thing, for the anchors it should be (#how-it-works) and (#additional-resources)

**Comment by nomiko0626** [comment]
Fixed it.

**Review by kaavyakalani26 — APPROVED** [review]
Looks all good now! Thank you.

**Pull request merged**
