### PR TITLE
Introduction to Nginx

### PR DESCRIPTION
**Pull request by lukecheseldine**
A friendly introduction to Nginx!

### CODE REVIEW

**Review by danielqiuu — CHANGES_REQUESTED** [review]
Overall, this is a comprehensive overview and setup instructions on Nginx. I like how you had linked external resources and pictures that might come in handy when setting up Nginx, it makes it beginner friendly. 
You did talk about installing Nginx on a Linux server, would it be possible to provide resources for install Nginx on other OS's, potentially for teams that might have a Windows server or something. 
Dont forget to add your page in the ```Development_Process.md``` file so that others can access your page.

**Comment by lukecheseldine** [comment]
> Overall, this is a comprehensive overview and setup instructions on Nginx. I like how you had linked external resources and pictures that might come in handy when setting up Nginx, it makes it beginner friendly. You did talk about installing Nginx on a Linux server, would it be possible to provide resources for install Nginx on other OS's, potentially for teams that might have a Windows server or something. Dont forget to add your page in the `Development_Process.md` file so that others can access your page.

@danielqiuu thanks for the feedback! I think instructions for other operating systems is a great idea, I'll look for some resources on that! Good catch on adding my page to `Development_Process.md` as well!

**Review by liu-samuel — CHANGES_REQUESTED** [review]
Hey Luke! This is a great introduction and I really like the picture you included to help vizualize what Nginx is doing. Your description of what Nginx does is also comprehensive. I would just like to suggest adding the pros and cons of Nginx compared to alternatives such as Apache and why it may be better.

**Comment by lukecheseldine** [comment]
> Overall, this is a comprehensive overview and setup instructions on Nginx. I like how you had linked external resources and pictures that might come in handy when setting up Nginx, it makes it beginner friendly. You did talk about installing Nginx on a Linux server, would it be possible to provide resources for install Nginx on other OS's, potentially for teams that might have a Windows server or something. Dont forget to add your page in the `Development_Process.md` file so that others can access your page.

Thanks for those comments @danielqiuu ! I've added instructions for Mac and Windows, and added my page to `Development_Process.md` table of contents. Could you give me another review when you get a moment? Thanks! 🤠

**Review by liu-samuel — APPROVED** [review]
This looks good Luke! You picked an interesting topic and the information is great!

**Review by danielqiuu — APPROVED** [review]
This looks like a great tutorial for many teams that might be interested in using Nginx for their CSC301 project. I think your autoformatter changed ```Development_Process.md``` but I'm sure you can fix any merge conflicts before merging. Good stuff Luke!

**Pull request merged**
