### PR TITLE
Added tutorial for LLM Testing & Debugging

### PR DESCRIPTION
**Pull request by Kai15116**
Added tutorial for using Large Language Model (LLM) like ChatGPT for testing and debugging purposes. 

**Key contents** 
- Added simple examples and techniques on how to use LLM for debugging
- Introduced major ways of using LLM for testing: 
  - Generating test cases directly
  - Generating test data
  - Generating user persona
-  Listed advantages and disadvantages of using LLM for testing and debugging

### CODE REVIEW

**Review by hanshhh — CHANGES_REQUESTED** [review]
LLM testing and debugging is a great topic to be included as a part of the wiki. Nice work for making the step by step explanation supportive for CSC301 students who are  new to this concept. I like the clean format and the comprehensive content.

Here are two things you might want to consider:
1. Maybe it's a good idea to add small explanation on few-shot learning since that is  also a good topic that people can cover when they want create to more advanced prompts for testing + debugging. 
2. And you could also add some links to external source that illustrates the test data generation, since that could be a great reference for the users trying to get an idea of how the generation process works.

**Comment by Kai15116** [comment]
> LLM testing and debugging is a great topic to be included as a part of the wiki. Nice work for making the step by step explanation supportive for CSC301 students who are new to this concept. I like the clean format and the comprehensive content.
> 
> Here are two things you might want to consider:
> 
> 1. Maybe it's a good idea to add small explanation on few-shot learning since that is  also a good topic that people can cover when they want create to more advanced prompts for testing + debugging.
> 2. And you could also add some links to external source that illustrates the test data generation, since that could be a great reference for the users trying to get an idea of how the generation process works.

You raised a good point. In my past intern, I worked on few-shot learning and had some website that was useful so I can also include that too. 
I am also going to add the source for test data generation that you mentioned. 
Thanks!

**Comment by Kai15116** [comment]
@hanshhh 
I added the requested change. 
Now there is external source for test data generation and I added the section at the bottom introducing few-shot examples. 
By the way, do you think it would be better to have list of recommended LLMs to use?

**Comment by hanshhh** [comment]
> @hanshhh
> I added the requested change.
> Now there is external source for test data generation and I added the section at the bottom introducing few-shot examples.
> By the way, do you think it would be better to have list of recommended LLMs to use?

It's great that you have provided those external sources I found useful during the internship. I believe it would be also beneficial for other readers. The few-shot learning really levels up the content. And to your question, it's definitely good to add a list of recommended LLMs if possible.

**Review by KareemSalem7 — CHANGES_REQUESTED** [review]
This is a great start, I love how you explain the process of LLM testing and flesh it out with code examples and explanations. However, I think including a dedicated section in your material that underscores the significance of traditional testing methodologies would be great. Highlighting their relevance can serve as a reminder for readers not to overlook foundational testing steps, and encourage a modular testing approach in your guide.

Additionally, consider including a brief explanation advising users to consult the course guidelines when integrating the material into their coursework. This proactive step can guide learners in aligning their studies with specific coursework requirements, promoting a more seamless integration of the learning material into their academic endeavors.

**Comment by Kai15116** [comment]
@KareemSalem7 
Thanks!
I will make a section that captures your feedback.

**Review by hanshhh — APPROVED** [review]
All the requests has been resolved. Nice job creating this tutorial, will be great asset for next semester 301 students. All the examples are accessible for beginner learning.  The links you provided are absolutely great sources. It's good to merge now!

**Review by KareemSalem7 — APPROVED** [review]
This looks great, it provides the user who has no experience to LLMs effectively, goes through testing, data examples, and sources to review for the user. Great guide and improvements based on feedback.

**Pull request merged**
