### PR TITLE
Added Angular Resources

### PR DESCRIPTION
**Pull request by Angada28**
Added brief Angular introduction and resources

### CODE REVIEW

**Comment by MicheleMassa802** [comment]
Submission content looks good. Short and effective introduction paired with a fairly complete set of resources. It’s nice to see a submission on Angular too, given not all students might have taken CSC309, making this submission on Angular extra important as a possible starting point for those that don’t already have experience with a frontend framework.

Even though I see you tried to fix the merge conflict, it still is present as you have not provided enough spaces with respect to main (try putting the link to your file in Tech_Stacks.md at line 5 or below).

Apart from that, I have no complaints, as your structure is good, and the submission is clean. I think this PR will be worthy of being merged after you fix this conflict.

**Comment by MicheleMassa802** [comment]
There still is a merge conflict, maybe try to solve the conflict from within the GitHub web editor such that you place the React submission link above yours (the way it would result in main). If you have no experience with the web editor, you basically have to do: 
image
If it's not clear please ask me about it.

**Comment by Angada28** [comment]
Made a new branch to resolve previous conflicts.

**Comment by MicheleMassa802** [comment]
Conflict resolved by opening a new branch, and all else is still good, therefore, I am merging the PR.

**Pull request merged**
