### PR TITLE
Introduction to Static Typing in Python

### PR DESCRIPTION
**Pull request by larryworm1127**
This pull request adds information about static typing in Python. It discusses type system-related topics including:
- dynamic typing and static typing
- typing hinting in Python and how it can be utilized for static type analysis using the Mypy library
- the pros and cons of using type hints and static type checking in Python

### CODE REVIEW

**Comment by wang-henry** [comment]
You should probably add some links to the Python official documentation for type hints so that people who want to use a larger variety of types know where to find them.

**Comment by larryworm1127** [comment]
Thanks for the feedback. I have added the links to the documentations for both Python type hints and Mypy

**Comment by eric-pham** [comment]
I think you should try to be more consistent with the code example to minimize confusion. For example, the first function snippet uses `pass` while the second one uses `...`.

**Comment by larryworm1127** [comment]
Good suggestion! Let me change it.

**Review by wang-henry — APPROVED** [review]
LGTM

**Pull request merged**
