### PR TITLE
Create Flask_App_Deployment_Heroku.md to add information about Deployment

### PR DESCRIPTION
**Pull request by RJAK11**
This PR includes information about:

- The setup steps involved before deployment on Heroku
- Steps on how to deploy the Flask application from start to finish
- Methods to debug common issues

### CODE REVIEW

**Comment by anudevgill** [comment]
This is a super helpful tutorial! I like how you split the information up into steps to make it easier for someone who wanted to follow along to understand and execute on their repository/environment. However, one thing that wasn't clear to me was if the application has to be deployed manually or if it is automatically deployed after any changes to the repository. Could you perhaps add some clarification regarding this point?

**Comment by chenikabukes** [comment]
This is very helpful Rana! Looking through the steps I would like some clarification on two things:
1. What exactly is Gunicorn and what is it for (there's nice explanations for each of the other files purposes)?
2. I know that there is also the option of deploying through Heroku's website rather than using the CLI. Can you briefly explain how that works?

**Comment by RJAK11** [comment]
> This is a super helpful tutorial! I like how you split the information up into steps to make it easier for someone who wanted to follow along to understand and execute on their repository/environment. However, one thing that wasn't clear to me was if the application has to be deployed manually or if it is automatically deployed after any changes to the repository. Could you perhaps add some clarification regarding this point?

Thank you Anudev! That's a great point. I will add an explanation about this to the introduction.

**Comment by RJAK11** [comment]
> This is very helpful Rana! Looking through the steps I would like some clarification on two things:
> 
> 1. What exactly is Gunicorn and what is it for (there's nice explanations for each of the other files purposes)?
> 2. I know that there is also the option of deploying through Heroku's website rather than using the CLI. Can you briefly explain how that works?

Thank you for bringing that to my attention Chenika! I will address both of these of these points in my explanations.

**Comment by RJAK11** [comment]
I have added in all the changes that were recommended. Is there anything else I should add or improve to make the guide more helpful?

**Comment by anudevgill** [comment]
> I have added in all the changes that were recommended. Is there anything else I should add or improve to make the guide more helpful?

One final thing that comes to mind for the sake of clarity would be adding a quick explanation about the logs that Heroku provides for debugging purposes. I would imagine that that would be quite handy for a student reading this tutorial.

**Comment by RJAK11** [comment]
> > I have added in all the changes that were recommended. Is there anything else I should add or improve to make the guide more helpful?
> 
> One final thing that comes to mind for the sake of clarity would be adding a quick explanation about the logs that Heroku provides for debugging purposes. I would imagine that that would be quite handy for a student reading this tutorial.

Thank you for your feedback! I've added a list of logs Heroku offers and what information each provides.

Do you think its ready now for merging?

**Review by anudevgill — APPROVED** [review]
Everything looks good to me now! Great work Rana!

**Review by chenikabukes — COMMENTED** [review]
Nice job working on the fixes. Looks great! Ready to merge.

**Review by chenikabukes — APPROVED** [review]
Nice job working on the fixes! Looks great, ready to merge.

**Comment by chenikabukes** [comment]
> > I have added in all the changes that were recommended. Is there anything else I should add or improve to make the guide more helpful?
> 
> One final thing that comes to mind for the sake of clarity would be adding a quick explanation about the logs that Heroku provides for debugging purposes. I would imagine that that would be quite handy for a student reading this tutorial.

I agree with Anudev, this is very useful for a student trying deployment on Heroku for the first time.

**Pull request merged**
