### PR TITLE
add openmp overview

### PR DESCRIPTION
**Pull request by justinwli930**
- add openmp overview
- add openmp programming model
- add very simple examples

#419

### CODE REVIEW

**Review by maxkmy — CHANGES_REQUESTED** [review]
Looks good. For the calculating the sum of an array in parallel, would it be possible to add a sequential version? I think it makes understanding parallel code in OpenMP is not so different from sequential code.

**Comment by justinwli930** [comment]
> Looks good. For the calculating the sum of an array in parallel, would it be possible to add a sequential version? I think it makes understanding parallel code in OpenMP is not so different from sequential code.

Good point! Will add it.

**Review by maxkmy — COMMENTED** [review]
Looks good. Thank you for making this change!

**Comment by leowrites** [comment]
Looks good. I like the examples but could you explain a bit about the clauses that you are using (specifically what `reduction` and `for` are doing?)

**Comment by justinwli930** [comment]
> Looks good. I like the examples but could you explain a bit about the clauses that you are using (specifically what `reduction` and `for` are doing?)

Good point. Will do!

**Review by maxkmy — APPROVED** [review]
Looks good to me.

**Review by leowrites — APPROVED** [review]

**Pull request merged**
