### PR TITLE
Add Kanban Introduction and Methodology

### PR DESCRIPTION
**Pull request by Tommy-Gong**
A Markdown file focused on Kanban. 
1. Basic Introduction to Kanban: The document starts with a foundational overview of Kanban, outlining its principles and significance in a software development context. This section provides a solid base for newcomers to understand the core concepts of Kanban.

2. Building a Kanban System: I have detailed a step-by-step guide on establishing a Kanban system. This guide is designed to be practical and easy to follow, helping team members implement Kanban in their workflows effectively.

### CODE REVIEW

**Comment by Krystal-Miao** [comment]
Hey Tommy, great job on the Kanban wiki so far! Your explanation of the foundational overview, principles, and significance of Kanban is solid. However, I noticed that you've pushed three graphs to GitHub, but they're not included in your explanation. Adding these graphs would significantly enhance readers' understanding of the concepts you're explaining.

**Comment by Tommy-Gong** [comment]
> Hey Tommy, great job on the Kanban wiki so far! Your explanation of the foundational overview, principles, and significance of Kanban is solid. However, I noticed that you've pushed three graphs to GitHub, but they're not included in your explanation. Adding these graphs would significantly enhance readers' understanding of the concepts you're explaining.

Thanks for your review, I was debugging the embedded pictures and forgot to uncomment them. 
I have corrected the PNG files,

**Comment by Krystal-Miao** [comment]
Hi Tommy,

I checked out the updated pictures, and your page looks great! After going through it again, I think the format is spot on. However, I believe we could enhance the section on starting a new Kanban process. Providing more emphasis on the steps involved would offer readers a clearer guide for implementation. Keep up the good work!

**Comment by Tommy-Gong** [comment]
> Hi Tommy,
> 
> I checked out the updated pictures, and your page looks great! After going through it again, I think the format is spot on. However, I believe we could enhance the section on starting a new Kanban process. Providing more emphasis on the steps involved would offer readers a clearer guide for implementation. Keep up the good work!

Are you suggesting to include a thorough explanation of how to implement a kanban system？ that's a good suggestion！
I'm also aiming to use the CSC301 project as an example background to further simplify the process which should benefit the CSC301 students.

**Comment by Tommy-Gong** [comment]
I've uploaded the revised version of my file.

**Comment by Krystal-Miao** [comment]
The pull request "Add Kanban Introduction and Methodology" is a comprehensive guide to implementing Kanban in software engineering. It's structured well, covering Kanban's concept, its benefits, differences from Scrum, and practical steps for implementation. The addition of visuals aids understanding. Overall, it's a valuable contribution, but additional examples and clearer explanations would make it even more impactful. Good job, Tommy!

**Comment by Tommy-Gong** [comment]
> The pull request "Add Kanban Introduction and Methodology" is a comprehensive guide to implementing Kanban in software engineering. It's structured well, covering Kanban's concept, its benefits, differences from Scrum, and practical steps for implementation. The addition of visuals aids understanding. Overall, it's a valuable contribution, but additional examples and clearer explanations would make it even more impactful. Good job, Tommy!

Thank you Krystal, for taking the time to review my pull request. I appreciate your suggestion to include more examples and clearer explanations. Thanks again for your constructive feedback. It's invaluable in helping me improve the quality of the content.

**Comment by zhg-kj** [comment]
Hi friend, your PR is breaking the entire repo's GH actions. Please fix

**Comment by Tommy-Gong** [comment]
> Hi friend, your PR is breaking the entire repo's GH actions. Please fix
Hello, Thanks for reminding me. Is the GH action resolved or is it still broken?

**Review by Krystal-Miao — COMMENTED** [review]
All good tommy!

**Pull request merged**
