### PR TITLE
Add The 'cat' Command Guide

### PR DESCRIPTION
**Pull request by donnaqi**
I have added a guide for the 'cat' command in the software tools section, related to issue  #407

### CODE REVIEW

**Comment by Raymond0721** [comment]
Hi Donna, I feel your overall format and writing is good. Well down! The only suggestion for me is adding some screenshots from you side to help us better understand the command. for instance, a simple about appending text into a file would be great!🚀

**Comment by donnaqi** [comment]
> Hi Donna, I feel your overall format and writing is good. Well down! The only suggestion for me is adding some screenshots from you side to help us better understand the command. for instance, a simple about appending text into a file would be great!🚀

I have added screenshots in the recent commit

**Comment by fonuxxine** [comment]
Hi Donna, I think that the article is well-written. I want to share one suggestion that the writing can share common usage of the cat command that helps programmers speed up their works. Otherwise, well done!

**Comment by donnaqi** [comment]
> Hi Donna, I think that the article is well-written. I want to share one suggestion that the writing can share common usage of the cat command that helps programmers speed up their works. Otherwise, well done!

I have added cat command usage that will likely speed up programmers' works in this commit: [5d3f2dd](https://github.com/learning-software-engineering/learning-software-engineering.github.io/pull/416/commits/5d3f2dd69f25b5409d360c7ede1d1acd8e8d6a2f)

**Pull request merged**
