### PR TITLE
Created New markdown file for the issue

### PR DESCRIPTION
**Pull request by Adrianhui123**
Created New markdown file for the issue with preliminary write ups for the Introduction and Understanding Section, Application section(Code Generation part), as well as Citation section

### CODE REVIEW

**Comment by sfnicholas** [comment]
Seems very good. 
I would like to have some examples within the first section of Introduction to Prompt Engineering, providing a high level image of what LLM does.

**Review by sfnicholas — COMMENTED** [review]
Quite good overall. I would like to have some examples within the first section of Introduction to Prompt Engineering, providing a high level image of what LLM does.

**Review by sfnicholas — CHANGES_REQUESTED** [review]
For citations, use a consistent format and provide a descriptive text for the links, so readers know what to expect when they click on them. Use eitherinline links and reference-style links.

**Comment by Adrianhui123** [comment]
> For citations, use a consistent format and provide a descriptive text for the links, so readers know what to expect when they click on them. Use eitherinline links and reference-style links.

Yeah i added a placeholder title for the link to make it more intuitive

**Comment by sfnicholas** [comment]
Can you add some commonly used LLM examples? so students can relate better what they are learning.

**Comment by Adrianhui123** [comment]
> Can you add some commonly used LLM examples? so students can relate better what they are learning.

Yes added some common examples, i also have
Imagine prompting an LLM with the sentence "The sunset over the ocean was a breathtaking sight," and the model continues with "as the hues of pink and orange painted a masterpiece in the sky, reflecting the day's end with a promise of renewal." This example showcases the model's ability to continue the narrative in a way that's contextually appropriate and stylistically coherent.

 for a common exmaple if you didn't see

**Comment by sfnicholas** [comment]
I find some interesting image that online, do you think it is good to add this picture? It will be more vivid to introduce what is pre-training and fine tuning. https://www.researchgate.net/publication/373642018/figure/fig1/AS:11431281185751651@1693796764125/Overview-of-LLM-training-process-LLMs-learn-from-more-focused-inputs-at-each-stage-of.png

**Comment by Adrianhui123** [comment]
> https://www.researchgate.net/publication/373642018/figure/fig1/AS:11431281185751651@1693796764125/Overview-of-LLM-training-process-LLMs-learn-from-more-focused-inputs-at-each-stage-of.png

I think it is rather too comprehensive, we are working on a more baisic understanding page

**Review by sfnicholas — CHANGES_REQUESTED** [review]
I think we are still missing our main heading... "Introduction to Prompt Engineering". 
Also could you add some headlines for each section?

**Pull request merged**
