### PR TITLE
Create kubernetes.md

### PR DESCRIPTION
**Pull request by kimxoals**

### CODE REVIEW

**Comment by MinGi-K** [comment]
I like how your post provides a thorough and comprehensive overview of Kubernetes, covering its key features and components in a well-structured manner. However, I feel like you can include more information about how a student might do a very basic setup as I think the average student will know or heard of Kubernetes but not know how to set it up if they decide to use it.

**Review by MinGi-K — CHANGES_REQUESTED** [review]
I like how your post provides a thorough and comprehensive overview of Kubernetes, covering its key features and components in a well-structured manner. However, I feel like you can include more information about how a student might do a very basic setup as I think the average student will know or heard of Kubernetes but not know how to set it up if they decide to use it.

**Review by MinGi-K — CHANGES_REQUESTED** [review]
Also, when might users use Kubernetes? I don't think there was a group yet that has used Kubernetes so far, so it might be good to outline a good use case or when someone might want to consider Kubernetes

**Comment by kimxoals** [comment]
> Also, when might users use Kubernetes? I don't think there was a group yet that has used Kubernetes so far, so it might be good to outline a good use case or when someone might want to consider Kubernetes

Yes thank you for your good point. A intro should also include a short set-up so that people can follow through with ease.

**Comment by kimxoals** [comment]
> Also, when might users use Kubernetes? I don't think there was a group yet that has used Kubernetes so far, so it might be good to outline a good use case or when someone might want to consider Kubernetes

I've added both technical and a real life user case so that a person completely new to K8 can get a better application of what it is capable of doing.

**Review by MinGi-K — CHANGES_REQUESTED** [review]
Hey Taemin, there seem to be some typos and some unfinished sentences in your entry. For example, "scailing" and a sudden sentence ending in "favo". I would check over your entry and proof read it once again!

**Comment by kimxoals** [comment]
> Hey Taemin, there seem to be some typos and some unfinished sentences in your entry. For example, "scailing" and a sudden sentence ending in "favo". I would check over your entry and proof read it once again!

Thanks for pointing it out! I fixed all the grammar mistakes

**Comment by kimxoals** [comment]
> Also, I would either just provide a link for the setup instruction, or also provide setup instructions for other OS as well

Thanks Mingi, I have removed the step by step guide and put a link to various environment set up instead

**Comment by MinGi-K** [comment]
Okay! Overall I think your contribution provides a comprehensive overview of Kubernetes and provides nice resources for future CSC301 students to get started if they decide to use Kubernetes in the future. Looks good to merge for me!

**Pull request merged**
