### PR TITLE
Accessibility write-up

### PR DESCRIPTION
**Pull request by Amyh102**
Accessibility in User Experience topic

### CODE REVIEW

**Comment by Plopstuff** [comment]
I like the structure and information highlighted! Maybe give an example of what would be considered bad for accessibility vs good?

**Review by Plopstuff — CHANGES_REQUESTED** [review]
I like the structure and information highlighted! Maybe give an example of what would be considered bad for accessibility vs good?

**Comment by Amyh102** [comment]
> I like the structure and information highlighted! Maybe give an example of what would be considered bad for accessibility vs good?

Good point - I'll add some examples to the section below about user design

**Review by Plopstuff — APPROVED** [review]
I like the addition! Including resources for such examples is definitely a good idea, its usually overwhelming to figure out your own examples.

**Pull request merged**
