### PR TITLE
Create tfidf-scikit

### PR DESCRIPTION
**Pull request by keviny15**
initial commit

### CODE REVIEW

**Review by nomiko0626 — COMMENTED** [review]
Overall, the content is clear and concise. However, providing a specific example would enhance the clarity of the explanation. For instance, you could consider using a simple sentence as a sample document and demonstrate what the resulting TF-IDF matrix would look like.

**Comment by keviny15** [comment]
> Overall, the content is clear and concise. However, providing a specific example would enhance the clarity of the explanation. For instance, you could consider using a simple sentence as a sample document and demonstrate what the resulting TF-IDF matrix would look like.

Thanks for your feedback! I will make some changes and do a new commit.

**Comment by nomiko0626** [comment]
Looks good! You can merge it now.

**Comment by nomiko0626** [comment]
In step 4, could you provide a more detailed explanation of the parameters?

**Comment by nomiko0626** [comment]
Looks good! Could you also include more specific use cases for it?

**Pull request merged**
