### PR TITLE
Seven Rules of Thumb for Website Experimenters utilizing A/B testing

### PR DESCRIPTION
**Pull request by fonuxxine**

### CODE REVIEW

**Comment by Raymond0721** [comment]
Hi Samira! I think you are doing well, but consider highlighting the importance of clear objectives and user feedback in your overview. It's crucial to define what success looks like for each experiment and actively seek out user feedback to understand the impact of changes beyond just metrics. This approach ensures that the experiments align with user needs and preferences, leading to more meaningful improvements.

**Review by donnaqi — COMMENTED** [review]
To keep the project's commit history clean and navigable, it's helpful if you may squash small commits related to the same feature or fix into a single commit before merging.

**Comment by fonuxxine** [comment]
> To keep the project's commit history clean and navigable, it's helpful if you may squash small commits related to the same feature or fix into a single commit before merging.

I'll squash when merging to keep the history clean.

**Comment by fonuxxine** [comment]
> define what success looks like for each experiment and actively seek out user feedback to understand the impact of changes beyond just metrics. This approach ensures that the experiments align with user needs and preferences, leading to more meaningful improvements.

The writing touched on this when talking about conducting small-scaled experiments and seeking verbatim feedback. I added this points at the end to emphasize flexibility and personalized experiment design towards more meaningful improvements.

**Pull request merged**
