### PR TITLE
Introduction to Flask and Flask-SQLAlchemy

### PR DESCRIPTION
**Pull request by tejcapildeo**
This is the introduction to Flask, specifically including the usage of Flask-SQLAlchemy as the database solution. This is the first draft, as it will be reviewed by other group members and changes will be made to improve it. The aim is to explain what each technology is and its benefits, then explain the installation, and finally give some insight on how to use these technologies.

### CODE REVIEW

**Comment by VinayakMaharaj** [comment]
Good job with the overview you gave on Flask-SQLAlchemy as the database solution, seems very thorough! I suggest however that you maybe include some videos in addition to the documentation linked, maybe can be an overview video on this tool or maybe even a video similar to this can work https://youtu.be/uZnp21fu8TQ?si=c46Sk4QzZCIMn9Lf

**Comment by tejcapildeo** [comment]
That's a great idea. This video seemed really useful for getting into Flask-SQLAlchemy, so I went ahead and added it to the Additional Resources section. I also added a link to more documentation in that section as well.

**Comment by VinayakMaharaj** [comment]
Overall it looks really nice, just to improve visibility can you use markdown formatting to bold certain key points, can you also use ordering for your steps to setup and make the links look nicer by clicking a word instead of the link directly

**Comment by tejcapildeo** [comment]
I made the changes, and I think this helps improve the readability of the document. I was wondering though, do you think I should add some more about what to do if the user is getting trouble with Flask?

**Comment by VinayakMaharaj** [comment]
Yes, I think that would be really helpful. Maybe you can include some helpful documentation for common errors and how to troubleshoot them.

**Comment by Dario1031** [comment]
Your guide looks great! I was thinking that you could include the terminal commands to install flask and flask-sqlalchemy inside of the report itself (even though you've already linked the guides) to make it easy to copy and paste.

**Comment by tejcapildeo** [comment]
That's a good idea. I just made the changes, and I agree that this will make it easy for the reader to find and reference the installation commands.

**Pull request merged**
