### PR TITLE
Tech Stack: Added React Components Guide

### PR DESCRIPTION
**Pull request by KareemSalem7**
Welcome to my PR on React Components. I created a file called React_Components.md that will make you a pro 100 percent just read and learn everything possible.

- Understand a quick rundown of what react components are and how they came about
- Learn why we need to use a react component and where
- Provides a step by step on how to use react components to track data and promote modularity in your code
- Difference between class and functional component, understanding the advantages and disadvantages, and what context to use which one in

hope you enjoy this guide

### CODE REVIEW

**Review by Kai15116 — CHANGES_REQUESTED** [review]
Looks great. Your explanation are easy to understand and very organized. 

One suggestion I can make is to add section for listing sources to describe what the user can look for more details. Also, if you have any resources you used to write this content, you should add link to those too. 

This is very minor, but you can also use `this style` to make it easier for people to read the coding component since that seems to be missing in the section, "Managing State With Functional Components: useState Hooks".

**Review by hanshhh — CHANGES_REQUESTED** [review]
Nice job creating an intuitive tutorial for the React reusable components! The breakdown and instructions are easy to follow, making it engaging and accessible to React beginners. I also like the part about the difference between class Component and Functional components.

There are two things you can consider for the following writeup:
1. One potential improvement is to have code examples for class and functional components so readers can easily distinguish them. 
2. You could also add a table of content that helps with the navigation once the page grows after the code examples are added.

**Comment by KareemSalem7** [comment]
ok I have made those changes thanks

**Review by Kai15116 — CHANGES_REQUESTED** [review]
The changes looks good!
Sources are now added and the style for code components are updated. 

Sorry that I missed this on the first review, but maybe it might be good to add some common mistakes because I think @hanshhh's common mistakes section looked great.

**Review by hanshhh — CHANGES_REQUESTED** [review]
All the requests seems to be completed, the examples and comments are accurate and will be great examples for beginners to refer to. 

Do you think it would be better to add where user should put those components in the react application because I believe that's a quite essential part of reusable components when I was learning it and I had no idea how the folder structure should be like?

**Comment by KareemSalem7** [comment]
> All the requests seems to be completed, the examples and comments are accurate and will be great examples for beginners to refer to.
> 
> Do you think it would be better to add where user should put those components in the react application because I believe that's a quite essential part of reusable components when I was learning it and I had no idea how the folder structure should be like?

wow that's a great point thanks

**Comment by KareemSalem7** [comment]
ok I have included those latest changes having common mistakes for students to learn from and I included folder structure

**Review by Kai15116 — CHANGES_REQUESTED** [review]
All the changes looks great, but I think you should also add your link to your file [Tech_Stacks.md](https://github.com/learning-software-engineering/learning-software-engineering.github.io/blob/main/Topics/Tech_Stacks.md).

**Comment by KareemSalem7** [comment]
included link now

**Review by Kai15116 — CHANGES_REQUESTED** [review]
All changes that I requested seems to be completed. 

Good work!

**Review by Kai15116 — APPROVED** [review]
Sorry! I requested changes by accident. 

Approved!

**Review by hanshhh — APPROVED** [review]
Good job for all the hard work! It would be really helpful for the next semester CSC301 students if they read the this tutorial.

**Pull request merged**
