### PR TITLE
Serverless applications on google cloud

### PR DESCRIPTION
**Pull request by loveillusion**
I designed a module on building serverless applications using Google Cloud Functions. Topics could include setting up a Google Cloud environment, writing function code, and integrating with other cloud services.

### CODE REVIEW

**Review by leoyliu — CHANGES_REQUESTED** [review]
The section on Google Cloud Functions is a good start, but I would appreciate a deeper dive into the specific features and capabilities of Google Cloud Functions. Could you add more detailed explanations about the limitations, best practices for optimization, and how it compares with similar offerings from other cloud providers? This would help in understanding not just the 'how' but also the 'why' behind using Google Cloud Functions.

**Comment by loveillusion** [comment]
Thank you Leo for your input, I have added some content based on your suggestions! 👍

**Comment by leoyliu** [comment]
Hi Kevin, 

Observing your progress, I feel it would greatly benefit from including more practical examples. The theoretical foundation is solid, but learners, especially those new to serverless computing, could gain a deeper understanding if each section incorporated real-world scenarios or case studies.

**Comment by loveillusion** [comment]
I have added a code example for section 3, I also added a detailed guide on how to create a google account etc. in section 2

**Review by leoyliu — APPROVED** [review]

**Comment by leoyliu** [comment]
After reviewing the document, I believe that the content is comprehensive, well-structured, and covers the essential aspects of serverless computing in the Google Cloud environment. The theoretical foundations are robust and well-explained, offering a solid base for learners. Great job!

**Pull request merged**
