### PR TITLE
Added Apache_Superset.md into Tech-Stack directory

### PR DESCRIPTION
**Pull request by DavidM0808**
This is the first Pull Request from this branch. Here are the list of items added into the markdown file:
* Added a list of prerequisites for Apache Superset. The prerequisites are not necessasary but it would help with understanding how it works.
* Added introduction about Apache Superset: What apache superset is and what it can do.
* Added detailed instruction about setting up Apache Superset.
* Added a list of some common issues/warnings that user may encounter for one of the set-up methods.
* Added some extra resources about Apache Superset.

### CODE REVIEW

**Comment by justinzzy-code** [comment]
This resource looks like a great contribution learning how to install and set-up Apache Superset. This will help any future group in 301 that might be looking to use Apache Superset.

I have a few suggestions that you might want to look at: 

1) Under Extra Resources, maybe there could be an instruction to install docker desktop.
2) Maybe potential issues with installation of Apache Superset from scratch could be added.

**Comment by DavidM0808** [comment]
> This resource looks like a great contribution learning how to install and set-up Apache Superset. This will help any future group in 301 that might be looking to use Apache Superset.
> 
> I have a few suggestions that you might want to look at:
> 
> 1. Under Extra Resources, maybe there could be an instruction to install docker desktop.
> 2. Maybe potential issues with installation of Apache Superset from scratch could be added.

The instruction to install Docker Desktop can definitely help! I'll also look into the issues you can encounter when you install Apache Superset from scratch.

**Review by justinzzy-code — APPROVED** [review]
This changes look good. Docker Desktop is a good way to deploy Apache Superset on Windows.

**Comment by DavidM0808** [comment]
Changes since the last comment:
* Added an external link which has a detailed instruction on how to install Docker Desktop.
* Added some potential issues with setting up apache superset from scratch.

**Review by justinzzy-code — COMMENTED** [review]
For the part on "Potential Issues with Installing from Scratch", maybe it better to strictly state the suitable Python Version under a new section like "Development requirements"?

**Comment by DavidM0808** [comment]
> For the part on "Potential Issues with Installing from Scratch", maybe it better to strictly state the suitable Python Version under a new section like "Development requirements"?

Forgot to reply, but Development requirements is more specific to the deployment of Apache Superset, not necessarily the installation process. I stated the python version because it's a potential issue that users may come accross should they choose to install from scratch.

Deleting the branch as the PR has already been merged.

**Pull request merged**
