### PR TITLE
Create Salesforce_Social_Login.md

### PR DESCRIPTION
**Pull request by MinGi-K**

### CODE REVIEW

**Review by kimxoals — COMMENTED** [review]
There is a Salesforce API section already, consider merging the two pages? Or putting a link to the previous page.

**Comment by MinGi-K** [comment]
> There is a Salesforce API section already, consider merging the two pages? Or putting a link to the previous page.

On second thought you are right, I thought it was different enough to get its own page but I think it will be better if its integrated into the old Salesforce page as option 2. Deleted the new page and merged information into old page. Done!

**Comment by kimxoals** [comment]
> > There is a Salesforce API section already, consider merging the two pages? Or putting a link to the previous page.
> 
> On second thought you are right, I thought it was different enough to get its own page but I think it will be better if its integrated into the old Salesforce page as option 2. Deleted the new page and merged information into old page. Done!

The second authentication method you described seem to require a "connected app". Could you give some explanation to what it is? I don't think it is a common concept in SWE

**Comment by MinGi-K** [comment]
> > > There is a Salesforce API section already, consider merging the two pages? Or putting a link to the previous page.
> > 
> > 
> > On second thought you are right, I thought it was different enough to get its own page but I think it will be better if its integrated into the old Salesforce page as option 2. Deleted the new page and merged information into old page. Done!
> 
> The second authentication method you described seem to require a "connected app". Could you give some explanation to what it is? I don't think it is a common concept in SWE

I put in a brief explanation and also put in a link for further reading if the user is interested.

**Comment by kimxoals** [comment]
> > > > There is a Salesforce API section already, consider merging the two pages? Or putting a link to the previous page.
> > > 
> > > 
> > > On second thought you are right, I thought it was different enough to get its own page but I think it will be better if its integrated into the old Salesforce page as option 2. Deleted the new page and merged information into old page. Done!
> > 
> > 
> > The second authentication method you described seem to require a "connected app". Could you give some explanation to what it is? I don't think it is a common concept in SWE
> 
> I put in a brief explanation and also put in a link for further reading if the user is interested.

Looks good to me!

**Review by kimxoals — APPROVED** [review]
Look good to me!

**Pull request merged**
