### PR TITLE
Add example implementation guide for react native component

### PR DESCRIPTION
**Pull request by Cathypei**
I have created a guide for implementing a React Native component. 

The topics I included are:
- Setting up the React Native project
- Implementing the custom component 'ProductCard'
- Running the application

### CODE REVIEW

**Comment by gy2075338364** [comment]
Your guide on implementing custom React Native components is neatly organized, the step-by-step instructions making it easier to learn! Besides that, the actual code snippets is also very helpful for learners to understand and implement. With the comments you provided, each of codes' purposes are clarified. Overall, this guide is very clear and useful to me as a learner.

**Comment by gy2075338364** [comment]
I think maybe adding a new section about Error Handling and Debugging Tips would be a good idea. This section aims to help us learners with common issues we might encounter while working with custom components in React Native and how to effectively solve them.

**Comment by Cathypei** [comment]
I have added a debugging section that introduces using console logs for debugging and mentions some debugging tools that can be utilized. In the error handling section, I introduced the use of try-catch blocks to handle specific errors and provided a brief example of unit testing.

**Comment by gy2075338364** [comment]
Wow! I see now you have also added debugging tips and error handling, also unit-tests. These could provide a much more efficient way for learner to implement.

**Comment by gy2075338364** [comment]
I have only one other minor suggestion, maybe you can emphasize a bit on performance consideration. While rendering multiple custom React Native components, how might this impact the app performance. How might we optimize component rendering to enhance user experience?

**Comment by Cathypei** [comment]
Good point! I've added a performance section that discusses several strategies to optimize performance when rendering multiple components.

**Pull request merged**
