### PR TITLE
tech-stack: added NgRx state management to Angular.md

### PR DESCRIPTION
**Pull request by chenikabukes**
This PR contains:
- An introduction to state management in Angular using NgRx state management
- Installation requirements for NgRx
- Key parts of NgRx state
- NgRx Benefits
- NgRx Difficulties

### CODE REVIEW

**Comment by anudevgill** [comment]
This looks great and is very informative! However, I would recommend adding examples of each of the key parts of the state to make it easier for someone with less front-end experience to understand.

**Comment by chenikabukes** [comment]
> This looks great and is very informative! However, I would recommend adding examples of each of the key parts of the state to make it easier for someone with less front-end experience to understand who may not have actually worked with NgRx state management before. These examples may make the concepts more relatable and easier to digest/understand.

Thank you for pointing that out Anudev! I will add some simple examples to each part of state to make the comprehensive state management system which is NgRx more clear.

**Comment by RJAK11** [comment]
This is really well-organized and easy to follow! This sounds like a very comprehensive state management system, can you add a brief explanation about if there are possible simplifications for when the database of your application gets too large to individually handle each update?

**Comment by chenikabukes** [comment]
> This is really well-organized and easy to follow! It sounds like a very comprehensive state management system, can you add a brief explanation about if there are possible simplifications for when the database of your application gets too large to individually handle each update?

Thanks for the feedback Rana! That's a great point, I will add an explanation about how we can use memoization in state to resolve this problem.

**Comment by chenikabukes** [comment]
@RJAK11 @anudevgill Hi reviewers! I have addressed your comments above and would like to confirm if there is anything else I should address, otherwise are we ready to merge?

**Comment by RJAK11** [comment]
Yup, that looks perfect to me. Great Job Chenika!

**Review by RJAK11 — APPROVED** [review]

**Comment by anudevgill** [comment]
> @RJAK11 @anudevgill Hi reviewers! I have addressed your comments above and would like to confirm if there is anything else I should address, otherwise are we ready to merge?

It looks great! The code snippets are particularly helpful in understanding the content!

**Review by anudevgill — APPROVED** [review]
Looks great! You can go ahead and merge!

**Pull request merged**
