### PR TITLE
Ethics 8 principles

### PR DESCRIPTION
**Pull request by winstonc03**
I updated the paragraph about the 8 principles of ethics in software engineering as suggested by the ACM/IEEE-CS Joint Task Force on Software Engineering Ethics. There now exists a link to an external MD file I created on the topic where I expanded on each of the principles.

### CODE REVIEW

**Comment by kevinzshen** [comment]
Hey Winston, the update looks great! I've reviewed the changes, and everything seems to be in order. However, I have a couple of suggestions to further enhance the document:  

• Add Visuals: It would be beneficial to include visuals to complement each of the principles. Visual aids can help reinforce the concepts and make the document more engaging for readers.  

• Bookmarks on Links: To improve organization and navigation, let's add bookmarks to each of the principles at the top of the document. This will allow readers to quickly jump to the specific principle they're interested in without having to scroll through the entire document.  

Once these enhancements are made, I believe the document will be even more informative and user-friendly. Let me know if you need any assistance with implementing these changes!

**Comment by winstonc03** [comment]
Hey Kevin,

Thanks for the feedback and suggestions, I'll work on adding visuals for some of the principles and include bookmarks at the top of the document for better organization and navigation.

**Comment by kevinzshen** [comment]
I see you have updated your PR with my suggested improvements, great work!

**Comment by winstonc03** [comment]
> I see you have updated your PR with my suggested improvements, great work!

Thanks for reviewing, will merge now.

**Pull request merged**
