### PR TITLE
Revert "Update Automated_Testing.md to add information about API testing"

### PR DESCRIPTION
**Pull request by anudevgill**
Reverts learning-software-engineering/learning-software-engineering.github.io#127 to add headings

### CODE REVIEW

**Comment by anudevgill** [comment]
I just added the headings that Chenika mentioned! I missed this earlier. Let me know if everything looks good to merge again!

**Comment by RJAK11** [comment]
That looks perfect to me. Great job Anudev!

**Review by RJAK11 — APPROVED** [review]

**Review by chenikabukes — APPROVED** [review]
The heading sections perfectly summarise the content! I haven't used headings smaller than ### in markdown yet, but if this aligns with the rest of the file's heading sizes, then it looks good to me and can be merged in :)

**Comment by anudevgill** [comment]
> The heading sections perfectly summarise the content! I haven't used headings smaller than ### in markdown yet, but if this aligns with the rest of the file's heading sizes, then it looks good to me and can be merged in :)

Did a double check and the headings do align with the rest of the file! I'll merge this in!

**Pull request merged**
