### PR TITLE
Create React-Toastify.md

### PR DESCRIPTION
**Pull request by IanQuan**
Toastify is a lightweight, flexible tool for presenting notifications in web applications. Known for its ease of use and integration, it allows developers to provide real-time feedback to users. Whether it’s to confirm an action, such as a file upload, warn about possible issues, celebrate successes, or inform users of errors, Toastify notifications are a user-friendly solution.

These notifications are particularly useful because they are non-intrusive; they don’t interrupt the user's workflow. This makes Toastify an essential tool in modern web development for enhancing user experience without requiring the user's immediate attention for less critical messages.

### CODE REVIEW

**Comment by IanQuan** [comment]
Toastify is a lightweight, flexible tool for presenting notifications in web applications. Known for its ease of use and integration, it allows developers to provide real-time feedback to users. Whether it’s to confirm an action, such as a file upload, warn about possible issues, celebrate successes, or inform users of errors, Toastify notifications are a user-friendly solution.

These notifications are particularly useful because they are non-intrusive; they don’t interrupt the user's workflow. This makes Toastify an essential tool in modern web development for enhancing user experience without requiring the user's immediate attention for less critical messages.

**Comment by Shaffaan** [comment]
Hey Ian,
First off, I must say, you've done an amazing job with the README. The layout is well-structured, and the table of contents makes navigation a breeze. I particularly appreciate how it starts with the basics, then dives into different notification types, placements, and the flexibility of customizations. However, I did notice that some links in the table of contents do not work.

To further enhance the README and aid developers in making quick decisions, I suggest delving a bit deeper into the different transition effects offered by toasts. Adding a section that explores these transitions with accompanying GIFs would be immensely beneficial. Visualizing the transitions in action would provide a clearer understanding and help developers choose the right option for their needs.

**Comment by IanQuan** [comment]
Thank you so much for the feedback! I have fixed the links in the table of contents and I agree that adding GIFs to demonstrate the transition effect would be helpful for developers to have a better idea of the end result quicker. I have made changes accordingly and feel free to comment on the update.

**Comment by Shaffaan** [comment]
Hey Ian, thankyou for the quick response. The readme looks amazing now and the transition effect looks nice. Good Work
Lets Get This Merged!!

**Pull request merged**
