### PR TITLE
Adding Prioritization Techniques

### PR DESCRIPTION
**Pull request by Umair-H**
Initial draft for explaining what common prioritization techniques can be implemented to help product development.

### CODE REVIEW

**Review by Jazli14 — CHANGES_REQUESTED** [review]
Amazing job Umair, this is looking great so far. I had a few considerations for your writeup however.

Try adding an introduction and conclusion to your section to help give readers contexts and wrap up your thoughts. Additionally with this addition, a table of contents could be useful to skip between sections.

**Comment by Umair-H** [comment]
> Amazing job Umair, this is looking great so far. I had a few considerations for your writeup however.
> 
> Try adding an introduction and conclusion to your section to help give readers contexts and wrap up your thoughts. Additionally with this addition, a table of contents could be useful to skip between sections.

Great idea I'll get to work on that!

**Review by Jazli14 — CHANGES_REQUESTED** [review]
Great improvements so far from the first iteration Umair.

I think some examples for the parts of both models would be nice additions, wherever they are possible. Just so students can help pinpoint what would fall in each category.

**Comment by Umair-H** [comment]
> Great improvements so far from the first iteration Umair.
> 
> I think some examples for the parts of both models would be nice additions, wherever they are possible. Just so students can help pinpoint what would fall in each category.

I Just added some examples trying to focus on the context of the 301 class. Let me know if anything would help make my file easier to read or more helpful. Thanks.

**Review by Jazli14 — CHANGES_REQUESTED** [review]
It's really coming together now Umair, just a few more changes I think you could add.

Add a section talking about how students can implement these techniques into their software development groups, how to choose between the two, and maybe add links to related resources. Then I think it would be perfect.

**Comment by Umair-H** [comment]
> It's really coming together now Umair, just a few more changes I think you could add.
> 
> Add a section talking about how students can implement these techniques into their software development groups, how to choose between the two, and maybe add links to related resources. Then I think it would be perfect.

Thanks for the insight.

I'll get right on incorporating these enhancements to ensure the content offers practical insights for students. If you have any specific areas you'd like me to emphasize or if there are particular resources you have in mind, please feel free to share them. I aim to make the content as comprehensive and beneficial as possible. Looking forward to delivering an even more valuable resource!

**Review by Jazli14 — APPROVED** [review]
This looks amazing Umair!

This is fantastic work! Your contribution is extremely valuable, particularly for all computer science students learning about trying to become a better product manager. Great job applying all of my feedback and creating a valuable article!

**Comment by Umair-H** [comment]
> This looks amazing Umair!
> 
> This is fantastic work! Your contribution is extremely valuable, particularly for all computer science students learning about trying to become a better product manager. Great job applying all of my feedback and creating a valuable article!

Thanks for the valuable feedback Jazli, I hope this article can help streamline the project process for 301 students as it can be pretty difficult to have a clear idea of the task at hand with so many things to worry about. 

Merging now!

**Pull request merged**
