### PR TITLE
Create Regex.md

### PR DESCRIPTION
**Pull request by kellythle**
Created Regex.md with an introduction, basic regular expressions, and extra resources

### CODE REVIEW

**Comment by kellythle** [comment]
Thank you for your suggestions. I have:
- Added language support sections
- Added examples for each regular expression pattern
Let me know if there is anything else I should add or change!

**Comment by JiwooJiyof** [comment]
The additional changes make the documentation a lot more clear and easier to understand. Another point I want to suggest is adding a visual diagram of how Regex is interpreted. Also, the documentation could become a lot more practical if there is a common use case examples. For example, you could add in email validation or website URL matching.

**Comment by kellythle** [comment]
Thank you again for your suggestions. I feel that students can definitely benefit from common case uses and understanding where regex can be applied. I have:
- Added a section for common case uses with examples and explained why some of these may not always be practical
- Added an additional resource for visualizing an inputted regex through railroad diagrams

Please let me know if there are other parts I can add or change!

**Comment by JiwooJiyof** [comment]
The addition of greedy vs. lazy quantifiers look very well-explained. Currently, the table of contents does not work properly for me. After that has been resolved, the branch should be good to merge.

**Comment by kellythle** [comment]
Great catch! Thank you. I have fixed the table of contents and it seems to work properly now. Please feel free to merge the branch if everything works!

**Comment by JiwooJiyof** [comment]
Everything looks great. I merged your branch. Great work!

**Pull request merged**
