### PR TITLE
Added resources about WebRTC 

### PR DESCRIPTION
**Pull request by davidlin2k**
The PR introduces a thorough expansion to our WebRTC documentation. The update includes detailed explanations of core concepts like the signaling server, ICE candidates, STUN and TURN servers, and the nuances of establishing connections and streaming in WebRTC. Additionally, it explores alternative architectures such as SFU and MCU, addressing their scalability and applicability in different scenarios.

Key Additions:

* **Introduction to WebRTC:** Clarifies the functionality and significance of WebRTC in modern web applications.
* **In-depth Analysis of Signaling Servers:** Explains their role and functionality in WebRTC architecture.
* **Detailed Explanation of ICE Candidates and Their Types:** Offers insights into the technicalities of WebRTC connections.
* **Roles of STUN and TURN Servers:** Discusses their importance in overcoming networking challenges.
* **Streaming Process:** Details the steps involved in streaming audio and video between peers.
* **Alternative Architectures (SFU and MCU):** Provides an analysis of these architectures, highlighting their scalability and use cases.

Purpose:

* To enhance the depth and breadth of our WebRTC documentation, providing a valuable resource for developers.
* To clarify complex concepts and streamline the learning process for those new to WebRTC.
* To offer insights into choosing the right architecture for specific WebRTC use cases.

### CODE REVIEW

**Comment by zhg-kj** [comment]
This is looking really good David. A few comments:

- The explanations are super clear and easy to follow, making it a breeze for anyone diving into WebRTC.
- Love how you've divided things up into sections; makes it all super digestible.

- How about hinting at what's to come with WebRTC? Just a quick snapshot to get readers excited about what they're diving into.
- Adding a simple diagram to explain ICE candidates could be a game-changer. Visuals can make this tech stuff a lot friendlier.
- Expanding more on SFU and MCU would be nice. Let's talk about their unique perks and limitations to give readers a fuller picture.

**Comment by davidlin2k** [comment]
> This is looking really good David. A few comments:
> 
> * The explanations are super clear and easy to follow, making it a breeze for anyone diving into WebRTC.
> * Love how you've divided things up into sections; makes it all super digestible.
> * How about hinting at what's to come with WebRTC? Just a quick snapshot to get readers excited about what they're diving into.
> * Adding a simple diagram to explain ICE candidates could be a game-changer. Visuals can make this tech stuff a lot friendlier.
> * Expanding more on SFU and MCU would be nice. Let's talk about their unique perks and limitations to give readers a fuller picture.

Thanks Kai for the feedback and suggestions. Adding a diagram for ICE candidates is a great idea for better clarity and I'll expand on the SFU and MCU sections to detail their unique advantages and limitations. I'll update the PR soon with these enhancements.

**Comment by xuallenx** [comment]
Great Work David, I think you have done a great job at explaining concepts like signalling server and ICE candidates, as well as the importance of STUN and TURN servers in ICE.

1. The introduction provides a clear and concise overview of WebRTC, making it accessible to readers who may be unfamiliar with the topic. The use of a rhetorical question engages the reader.

2. The explanation of the signaling server is informative, and the provided code example enhances understanding. The example signal structure is clear and adds practical value.

3. I like how you mentioned the option of hosting your own TURN server, as this adds a practical aspect to your explanations.

I agree with Kai that a simple diagram to explain ICE candidates would be extremely helpful, and if you have time I believe that adding quick code comments to critical parts of the code would benefit some readers, especially those who are new to coding and WebRTC as a whole! Keep up the great work!!

**Comment by davidlin2k** [comment]
I think the documentation on the perks and limitations of SFU and MCU is sufficient in the article. This article mainly focuses on establishing a peer-to-peer models and more details on SFU and MCU is also referenced at the end if the reader wants to learn more about different architectures.

**Pull request merged**
