### PR TITLE
Added guide to CSS Animation 

### PR DESCRIPTION
**Pull request by Arvingingoyon**
Added a new file that provides introductory information about CSS animation. It acts like a guide to getting started with CSS animation, talking about the key components (i.e. keyframes and animation properties) and how to use these animations.

### CODE REVIEW

**Comment by Arvingingoyon** [comment]
Hey thanks for the suggestions! I will definitely see if I can implement these changes.

I have a quick question regarding one of your suggestions, what specifically about the percentage keyframe part did you find difficult to understand? was it just the lack of information/explanation or did you find specific parts confusing?

**Comment by Arvingingoyon** [comment]
> Hey thanks for the suggestions! I will definitely see if I can implement these changes.
> 
> I have a quick question regarding one of your suggestions, what specifically about the percentage keyframe part did you find difficult to understand? was it just the lack of information/explanation or did you find specific parts confusing?

**Comment by Arvingingoyon** [comment]
> Hey the information is very concise and to the point which I really like. I also really liked the table of contents you included at the top. Here are some of my comments for your page:
> 
> * Adding examples of using the sub properties would be nice (concrete examples and what the animation looks like)
> * I found the "percentage keyframe" part a little difficult to understand, maybe elaborate a bit more for this.
> * For the "Using an animation" part, maybe elaborate a bit more on the tagging an animation to a component step. It makes sense to me since I had some prior knowledge on this, but for someone new it might seem a little confusing.
> 
> One more suggestion, including Gif for the animations you are talking about would be a great addition. It will be nice for the reader to have a visual representation of what each of the code chunks do ( just a suggestion 😄 ).

Hey thanks for the suggestions! I will definitely see if I can implement these changes.

I have a quick question regarding one of your suggestions, what specifically about the percentage keyframe part did you find difficult to understand? was it just the lack of information/explanation or did you find specific parts confusing?

**Comment by Raiyankr** [comment]
> Hey thanks for the suggestions! I will definitely see if I can implement these changes.
> 
> I have a quick question regarding one of your suggestions, what specifically about the percentage keyframe part did you find difficult to understand? was it just the lack of information/explanation or did you find specific parts confusing?

I think adding a bit more explanation in what it does will be helpful, or maybe including a picture. It will be easier to understand what it is doing.

**Comment by Arvingingoyon** [comment]
> > Hey thanks for the suggestions! I will definitely see if I can implement these changes.
> > I have a quick question regarding one of your suggestions, what specifically about the percentage keyframe part did you find difficult to understand? was it just the lack of information/explanation or did you find specific parts confusing?
> 
> I think adding a bit more explanation in what it does will be helpful, or maybe including a picture. It will be easier to understand what it is doing.

**Comment by Arvingingoyon** [comment]
Just added more information to the 'animation' sub-properties section to provide more information about each one. 

I decided not to include gifs or examples for each one because I believe some can't be easily shown with pre-exisitng gifs (ex. animation-play-state). Instead I just made each property text its own clickable link that redirects users to a web page dedicated to each.

**Comment by Arvingingoyon** [comment]
Rephrased to make the information about percentage keyframes more clear. Like 'animation' sub-properties, I decided to leave gifs or animation out as I feel as though this would clutter this section. However, I posted a link to them being used in the 'Using CSS animation section' towards the bottom of the page. This link showcases all of the content in use.

**Comment by Arvingingoyon** [comment]
Added more explanation to explain 'binding' animations to the 'Using An Animation' section as per your third suggestion

**Comment by Arvingingoyon** [comment]
Quick question, you mentioned adding animations/gifs/images to some of my sections to make things more visual, do you have any recommended sites/tools I can use to display that?

**Comment by Raiyankr** [comment]
> Just added more information to the 'animation' sub-properties section to provide more information about each one.
> 
> I decided not to include gifs or examples for each one because I believe some can't be easily shown with pre-exisitng gifs (ex. animation-play-state). Instead I just made each property text its own clickable link that redirects users to a web page dedicated to each.

This is a great change!

**Comment by Raiyankr** [comment]
> Added more explanation to explain 'binding' animations to the 'Using An Animation' section as per your third suggestion

It is definitely more clear and easier to follow along now, great explanation!

**Comment by Raiyankr** [comment]
> Quick question, you mentioned adding animations/gifs/images to some of my sections to make things more visual, do you have any recommended sites/tools I can use to display that?

I used some pictures from the W3School website. I think they have some great visuals you can include. I also linked a youtube video at the end. I saw that you also included a youtube video which I think is super helpful.

**Comment by Arvingingoyon** [comment]
> > Quick question, you mentioned adding animations/gifs/images to some of my sections to make things more visual, do you have any recommended sites/tools I can use to display that?
> 
> I used some pictures from the W3School website. I think they have some great visuals you can include. I also linked a youtube video at the end. I saw that you also included a youtube video which I think is super helpful.

I scanned through the W3School page on CSS animation and it seemed to only provide code snippets you can run, not gifs or images. I already linked the w3schools page in 'references and links' so readers can test this code out on their website.

**Pull request merged**
