### PR TITLE
Added content to the Giving and Receiving Feedback section

### PR DESCRIPTION
**Pull request by jchang0112**
Provides a feedback giving process that allows recipients to understand and accept feedback more easily, while feeling more positive emotions.

### CODE REVIEW

**Review by Eshchock1 — CHANGES_REQUESTED** [review]
Looks pretty good, like the content so far but here are some suggested changes:

- Consider changing the heading to just "Giving Feedback"
- Include specific examples for each step of delivering feedback
- Describe the impact of feedback more effectively

**Comment by jchang0112** [comment]
Could you clarify what exactly you mean by describing the impact of feedback more effectively? I have made the other changes asked, but I am not entirely sure how I could go about describing the impact, should I do something along the lines of comparing well delivered feedback to not well delivered feedback?

**Comment by Eshchock1** [comment]
> Could you clarify what exactly you mean by describing the impact of feedback more effectively? I have made the other changes asked, but I am not entirely sure how I could go about describing the impact, should I do something along the lines of comparing well delivered feedback to not well delivered feedback?

I've taken a look at your new changes, and they look good. When it comes to describing the impact of feedback I agree with comparing well-delivered feedback to not well-delivered feedback. Here are some suggestions in specific:
- Discuss in more detail why feedback is necessary and beneficial
- Consider discussing the difference between constructive/destructive feedback

**Comment by jchang0112** [comment]
I have made the changes you suggested, including an example of destructive feedback.

**Review by Eshchock1 — APPROVED** [review]
Nice changes, looks good to me!

**Pull request merged**
