### PR TITLE
Wenzhu/intro react navigation

### PR DESCRIPTION
**Pull request by wezhubb**
The first draft of react-navigation page

### CODE REVIEW

**Comment by wezhubb** [comment]
Hi team,

Here is the first draft of my page on react-navigation. Please leave comments on potential areas of improvement! Thanks!

Best,
Wenzhu

**Review by wezhubb — COMMENTED** [review]
Hi @selina-sha , I have addressed all your comments. Could you please review it again? Please let me know if you have any other suggestions! Thanks.

**Review by wezhubb — COMMENTED** [review]
changes reviewed

**Review by selina-sha — APPROVED** [review]

**Review by liuqin26 — COMMENTED** [review]
Hi Wenzhu,

Very well-organized introduction to react navigation. However, I have two suggestions below:

1. In the beginning paragraph, I think it would make more sense to include a real-life use case where the navigation method with parameters passsing functionality is highly needed. For example, when users click into their user profile page from the home page.

2. The limitation section felt a bit short for me. Can you explain what is Right-to-Left (RTL) Layout more and maybe more details on what we are expecting to see/do when run into this issue?

Overall, very useful content and all the coding chunks look correct to me.
- Qingyi

**Comment by wezhubb** [comment]
@liuqin26 Thank you for your detailed comment, it is very useful! I have addressed your concerns in the previous commit. Could you please review it and let me know if there are any further concerns. Thank you!

**Comment by liuqin26** [comment]
The lastest version looks great to me. We should be ready to merge this now!

**Pull request merged**
