### PR TITLE
Add page on Using VertexAI

### PR DESCRIPTION
**Pull request by nathan-cai**
Created a page for a quick start and introduction to using VertexAI an AI development platform offered by Google Cloud. In the page there is information on what VertexAI is, how to set it up, how to use it online, and how to use the PALM2 large language model by Google, in python through the VertexAI SDK. Further resources and learning are linked at the bottom of the page.

### CODE REVIEW

**Review by Asr161 — CHANGES_REQUESTED** [review]
Great guide, I think all the information is very clearly presented and you've made it easy for the reader to understand how to use VertexAI.

Just a minor concern: It would be beneficial if you could expand on the brief mention of the three types of generative AI (text, vision, and speech) available in VertexAI. Providing a short description or example of what each type can do would give readers a clearer understanding of the capabilities and applications of these AI models within VertexAI.

**Comment by nathan-cai** [comment]
Great point. I will add a brief description on the different types of generative AI that Google offers. Please let me know if there is anything else to change.

**Comment by nathan-cai** [comment]
I've just added a section about the different generative AI's that are offered, in the about VertexAI section. Please take a look and let me know if there is anything else for me to change.

**Review by Asr161 — CHANGES_REQUESTED** [review]
Great, good to see you've incorporated the feedback!
Another point to note, could you maybe add a general note explaining how your guide is applicable to CSC301 students in general?

**Comment by nathan-cai** [comment]
Nice Catch. Yes I will add a section on applications for 301 students into the conclusion.

**Comment by nathan-cai** [comment]
I just added a section on Applications specifically for 301 students. I also refined the conclusion a little. Please let me know if you notice any mistakes or if the branch is ready to be merged.

**Review by Asr161 — APPROVED** [review]
Everything looks good now, good job!

**Pull request merged**
