### PR TITLE
Nuxt 3 and Tailwindcss by Ibrahim bess

### PR DESCRIPTION
**Pull request by IbrahimBess**

### CODE REVIEW

**Review by lmg8 — COMMENTED** [review]
This is a well-organized and clearly written introduction to Nuxt3. I like that you provided a helpful YouTube tutorial & where to find support. I've personally never used this stack so I was wondering if there are advantages of using this framework over others? Since there are multiple tech stacks to choose from, it might be beneficial for other students to know this. 
Also, I think it would be helpful to update the table of contents on the README.md.

**Review by lmg8 — APPROVED** [review]
This looks good, thank you for writing down the pros and cons of Nuxt!

**Comment by IbrahimBess** [comment]
Thank you so much Img8

**Comment by jorjani** [comment]
@IbrahimBess can you please move Nuxt3 details to a file of its own under tech stack and the relevant sub stack? I merged before realizing you haven't done that. You can create a new PR for it

**Comment by IbrahimBess** [comment]
That is what I did in Patch-2 ( PR#14) in responding to your last comment. Merging PR14 and ignoring this PR should do it

**Pull request merged**
