### PR TITLE
Create Spring IoC file

### PR DESCRIPTION
**Pull request by leoyliu**
Explains the Inversion of Control and Dependency Injection with Spring.

### CODE REVIEW

**Review by loveillusion — CHANGES_REQUESTED** [review]
Great work on detailing the IoC concept in Spring! I believe this documentation could be further enhanced by adding diagrams or flowcharts. Visual representations of how the IoC container manages bean creation, lifecycle, and dependencies would make the concepts more accessible and easier to grasp, especially for those who are new to Spring or IoC.

**Comment by leoyliu** [comment]
Thank you for your valuable feedback. I completely agree that visual aids like diagrams and flowcharts can significantly enhance understanding, especially for complex concepts like IoC in the Spring Framework.

To address this, I plan to add a diagram that visually represents how the IoC container works in Spring.

**Comment by leoyliu** [comment]
I've included a diagram to illustrate the IoC container. Kindly review it and let me know if there are any further improvements I can make. Thanks!

**Review by loveillusion — CHANGES_REQUESTED** [review]
Your explanation of the IoC principle and its implementation in Spring is quite thorough. However, including some code examples, particularly showing the configuration of the IoC container and how dependencies are injected in a real-world scenario, would greatly improve understanding. This practical application view would be beneficial for developers looking to apply these concepts in their projects.

**Comment by leoyliu** [comment]
Thank you for your insightful feedback. I truly appreciate your suggestion to enhance the material with concrete code examples. To address this, I will be adding code example to the documentation.

**Comment by leoyliu** [comment]
I've added coding example to the document to demonstrate the configuration of the IoC container. Please review it and let me know if there are any additional improvements needed.

**Review by loveillusion — APPROVED** [review]
The explanation of IoC and how it is implemented in the Spring Framework is clear and accurate. It effectively communicates the core principles of dependency injection and how the Spring IoC container manages these dependencies. The technical details appear to be correct and well-explained. 

Overall, this pull request is informative and well-structured, offering a solid foundation for understanding Spring's IoC container.

**Pull request merged**
