### PR TITLE
Fix Beautiful Soup.md bugs

### PR DESCRIPTION
**Pull request by Kluckyyou**

### CODE REVIEW

**Comment by chenbriann** [comment]
Hi, I was attempting to merge my pull request https://github.com/learning-software-engineering/learning-software-engineering.github.io/pull/234 into the wiki but I found you have already created a file called BeautifulSoup.md and merged it. Is your entry on the signup form "Webscraping using Beautiful Soup and fetch data to Django Models" by Kevin You? If so, I have signed up earlier for this topic so unfortunately it is reserved. Please let me know if you signed up elsewhere but that was all I could find when I searched for "soup" in the spreadhsheet. Thanks.

**Comment by Kluckyyou** [comment]
> Hi, I was attempting to merge my pull request #234 into the wiki but I found you have already created a file called BeautifulSoup.md and merged it. Is your entry on the signup form "Webscraping using Beautiful Soup and fetch data to Django Models" by Kevin You? If so, I have signed up earlier for this topic so unfortunately it is reserved. Please let me know if you signed up elsewhere but that was all I could find when I searched for "soup" in the spreadhsheet. Thanks.

Hi, please see the A2 handout for reference on conflict in contribution. If you do not start merging it early, it's your responsibility to resolve the conflict. And I sent an email about this already to the TA and professor yesterday.

**Comment by Kluckyyou** [comment]
"This will likely happen if you leave things for the deadline. Do yourself a favor and start early. Make conflict resolution someone else’s problem! If not, you work with them to resolve the conflict. Managing conflicts is an inherent part of software engineering. If there are major merging issues, speak with your TA as early as possible." Let's see what the TAs and Professors say about this. I will let you know as soon as they respond my email. If this is permitted, I will delete that file I made, and use the 48-hour extension to finish the rest of the work. If not, you can use the 48-hour extension to finish the rest of the work. I am also planning to edit on a separate topic as a back-up plan. Which I also suggest you to do.

**Comment by Kluckyyou** [comment]
response
Hi, I am sorry this response could be disappointing to you. I would suggest you to edit on existing files to contribute or find another topic to contribute, and try to update your file as soon as possible after your partner left you feedback so you do not face conflict again.

**Comment by chenbriann** [comment]
Ok thanks, I will email the TA myself just to clarify and see what my next steps are.

**Pull request merged**
